# Generated by Django 5.2.4 on 2025-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField()),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
