# Generated by Django 5.2.4 on 2025-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto3_app', '0002_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('horario', models.TimeField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
