# Generated by Django 5.2.4 on 2025-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto3_app', '0003_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='descripcion',
            field=models.CharField(max_length=20),
        ),
    ]
